export const Button = (props: any) => null
export const Input = (props: any) => null
export const Label = (props: any) => null
export const Textarea = (props: any) => null
export const Dialog = (props: any) => null
export const DialogContent = (props: any) => null
export const DialogHeader = (props: any) => null
export const DialogTitle = (props: any) => null
export const Card = (props: any) => null
export const CardHeader = (props: any) => null
export const CardTitle = (props: any) => null
export const CardContent = (props: any) => null
export const Tabs = (props: any) => null
export const TabsList = (props: any) => null
export const TabsTrigger = (props: any) => null
export const TabsContent = (props: any) => null
export const Table = (props: any) => null
export const TableHeader = (props: any) => null
export const TableBody = (props: any) => null
export const TableRow = (props: any) => null
export const TableCell = (props: any) => null
export const Select = (props: any) => null
export const SelectTrigger = (props: any) => null
export const SelectValue = (props: any) => null
export const SelectContent = (props: any) => null
export const SelectItem = (props: any) => null
